/* Registro independiente de escenas: las repeticiones no cambian el progreso. */
window.CINEMATICS=[
 {id:'ignitia-launch',title:'Ignitia: despegue y caída',duration:38,description:'El despegue, el cable y un pasajero inesperado.'},
 {id:'ivan-descenso',title:'Iván descenso',duration:35,description:'Después de la caída, el bosque guarda el legado de Eric.'},
 {id:'intercepcion-espacial',title:'Intercepción espacial',duration:43,description:'Final alternativo · Sin Iván a bordo, Ignitia alcanza a Eric.',ending:'Eric bajo custodia… por ahora.'}
];
window.IvanDescent={state(t){return t<3?'fall':t<6?'impact':t<12?'cabin':t<16?'legacy':t<24?'newspaper':t<28?'allies':t<35?'light':'ending';}};
window.CinematicLibrary=class {
 constructor(){
  this.active=false;this.time=0;this.paused=false;this.finished=false;this.images={};
  for(const [key,path] of Object.entries({atlas:'assets/cinematics/ivan-descent-atlas.webp',wanted:'assets/cinematics/wanted-portraits.webp',ivan:'assets/sprites/ivan-walk-v2.png',ivanRight:'assets/cinematics/ivan-walk-right.webp',spaceAtlas:'assets/cinematics/space-interception-atlas.webp',prisonAtlas:'assets/cinematics/modern-prison.webp',burst:'assets/cinematics/space-explosion.webp',ignitiaRocket:'assets/cinematics/ignitia-star-rocket.webp',ericRocket:'assets/sprites/eric-cockpit-rocket.png',ericBody:'assets/sprites/dr-eric-standing.png'})){const image=new Image();image.src=path;this.images[key]=image;}
  document.querySelector('.controls').insertAdjacentHTML('beforeend','<button id="cinematics-open">▸ Cinemáticas</button>');
  document.querySelector('.scene-view').insertAdjacentHTML('beforeend',`<dialog id="cinematics-library"><div class="cinema-title"><h2>Cinemáticas de Astralia</h2><button id="cinematics-close" aria-label="Cerrar cinemáticas">×</button></div><p>Escenas guardadas. Puedes repetirlas sin cambiar tu partida.</p><div id="cinematics-list"></div></dialog>
   <dialog id="cinema-player"><div class="cinema-title"><span id="cinema-title"></span><button id="cinema-close" aria-label="Cerrar cinemática">×</button></div><div class="cinema-screen"><canvas id="cinema-canvas" width="960" height="540" aria-label="Cinemática de Astralia"></canvas><article id="cinema-newspaper" aria-label="Cartel de Karla con su retrato en blanco y negro" hidden><h2>SE BUSCA</h2><small class="wanted-archive">ARCHIVO DEL DR. ERIC</small><h3>KARLA</h3><p>Se cansó de escuchar «eso no lo vimos» y tener que explicar todo desde cero.</p></article><p id="cinema-ivan-line" hidden>Parece que todavía tengo aliados…</p><div id="cinema-end" hidden><p>Continuará en semana 10…</p></div></div><p id="cinema-caption" role="status"></p><div class="cinema-controls"><button id="cinema-pause">Pausar</button><button id="cinema-replay">Repetir</button><span id="cinema-time" aria-live="off"></span><button id="cinema-skip">Saltar cinemática</button></div></dialog>`);
  document.querySelector('.cinema-screen').insertAdjacentHTML('beforeend','<p id="cinema-eric-line" hidden></p>');
  this.menu=document.querySelector('#cinematics-library');this.player=document.querySelector('#cinema-player');this.canvas=document.querySelector('#cinema-canvas');this.ctx=this.canvas.getContext('2d');
  for(const item of CINEMATICS){const button=document.createElement('button');button.dataset.cinematic=item.id;button.innerHTML=`<strong>${item.title}</strong><span>${item.description}</span><small>Reproducir · ${item.duration} s</small>`;button.onclick=()=>this.play(item.id);document.querySelector('#cinematics-list').append(button);}
  document.querySelector('#cinematics-open').onclick=()=>this.open();document.querySelector('#cinematics-close').onclick=()=>this.close();
  document.querySelector('#cinema-close').onclick=()=>this.close(true);document.querySelector('#cinema-skip').onclick=()=>this.finish();document.querySelector('#cinema-replay').onclick=()=>{this.time=0;this.finished=false;this.paused=false;this.cues=new Set();this.stopEffects();Sound.selectBackground(this.item.id==='ivan-descenso'?'missing':'phase');if(Sound.enabled)Sound.play(Sound.sceneTrack);this.refresh();};
  document.querySelector('#cinema-pause').onclick=()=>{if(this.finished)return;this.paused=!this.paused;if(this.paused){this.stopEffects();Sound.tracks[Sound.sceneTrack].pause();}else{Sound.play(Sound.sceneTrack);if((this.item.id==='ignitia-launch'&&this.time>=8.5&&this.time<30.5)||(this.item.id==='intercepcion-espacial'&&this.time>=1&&this.time<6))Sound.play('rocket');}this.refresh();};
  for(const dialog of [this.menu,this.player])dialog.addEventListener('cancel',event=>{event.preventDefault();this.close(true);});
  new ResizeObserver(()=>this.resize()).observe(this.canvas.parentElement);window.addEventListener('astralia:language',()=>{if(this.item)this.refresh();});
 }
 enter(){if(this.active)return;this.active=true;this.previousTrack=Sound.sceneTrack;this.previousSilence=Sound.silence;Sound.silence=false;this.onToggle?.(true);window.dispatchEvent(new Event('astralia:ui-open'));}
 open(){if(this.canOpen&&!this.canOpen())return;this.enter();this.story=false;this.onComplete=null;this.item=null;if(this.player.open)this.player.close();this.menu.showModal();}
 play(id,{story=false,onComplete=null}={}){
  const item=CINEMATICS.find(c=>c.id===id);if(!item)return false;this.enter();this.item=item;this.story=story;this.onComplete=onComplete;this.time=0;this.paused=false;this.finished=false;this.cues=new Set();if(this.menu.open)this.menu.close();if(!this.player.open)this.player.showModal();
  if(id==='ignitia-launch'){this.legacy=Object.create(this.legacySource);this.legacy.scene=window.ESCAPE_ROOMS.find(r=>r.rocket);this.legacy.mode='launch';this.legacyRenderer=new EscapeRenderer(this.canvas);this.legacyRenderer.actors=new RoomActors();this.legacyRenderer.outdoor=new CastleExterior();}
  if(id==='intercepcion-espacial')this.space=new SpaceCinematic(this);
  document.querySelector('#cinema-end p').textContent=item.ending||'Continuará en semana 10…';
  Sound.selectBackground(id==='ivan-descenso'?'missing':'phase');this.resize();this.refresh();document.querySelector('#cinema-pause').focus({preventScroll:true});return true;
 }
 stopEffects(){for(const name of ['rocket','explosion','laugh'])Sound.stop(name);}
 close(completeStory=false){if(!this.active)return;const callback=completeStory&&this.story?this.onComplete:null;const story=this.story;this.active=false;this.item=null;this.finished=false;this.story=false;this.onComplete=null;this.menu.close();this.player.close();this.stopEffects();Sound.silence=this.previousSilence;if(!story||!completeStory){Sound.selectBackground(this.previousTrack);if(Sound.enabled&&!Sound.dead)Sound.play(this.previousTrack);}this.onToggle?.(false);callback?.();document.querySelector('#game').focus({preventScroll:true});}
 resize(){const rect=this.canvas.parentElement.getBoundingClientRect();if(rect.width<1)return;this.canvas.width=960;this.canvas.height=Math.round(960*rect.height/rect.width);if(this.item)this.draw();}
 tick(dt){if(!this.active||!this.item||document.hidden)return;if(!this.paused&&!this.finished){this.time=Math.min(this.item.duration,this.time+dt);this.audio();if(this.time>=this.item.duration){this.finish();if(!this.active)return;}}this.draw();}
 cue(key,time,fn){if(this.time>=time&&!this.cues.has(key)){this.cues.add(key);fn();}}
 audio(){if(this.item.id==='ivan-descenso'){this.cue('land',3,()=>Sound.tone(75,.3,'triangle',.18));this.cue('paper',16,()=>Sound.click());this.cue('light',28,()=>{Sound.click();Sound.selectBackground('villain');});}else if(this.item.id==='intercepcion-espacial'){this.cue('ignite',1,()=>Sound.play('rocket',true));this.cue('orbit',6,()=>Sound.stop('rocket'));this.cue('impact',17,()=>Sound.play('explosion',true));this.cue('chute',20,()=>{Sound.stop('explosion');Sound.selectBackground('transformation');});this.cue('bars',32.1,()=>{Sound.tone(150,.25,'triangle',.2);Sound.click();Sound.selectBackground('villain');});}else{this.cue('ignite',8.5,()=>Sound.play('rocket',true));this.cue('crash',30.5,()=>{Sound.stop('rocket');Sound.play('explosion',true);});}}
 finish(){if(!this.item)return;this.time=this.item.duration;this.finished=true;this.paused=true;Sound.stop('rocket');if(this.story){this.close(true);return;}this.refresh();this.draw();}
 refresh(){if(!this.item)return;document.querySelector('#cinema-title').textContent=this.item.title;document.querySelector('#cinema-pause').textContent=this.paused?'Reanudar':'Pausar';document.querySelector('#cinema-pause').disabled=this.finished;document.querySelector('#cinema-skip').disabled=this.finished;}
 background(cell,alpha=1,image=this.images.atlas){if(!image.complete||!image.naturalWidth)return null;const sw=image.naturalWidth/2,sh=image.naturalHeight/2,w=this.canvas.width,h=this.canvas.height,scale=Math.max(w/sw,h/sh),x=(w-sw*scale)/2,y=(h-sh*scale)/2;this.ctx.save();this.ctx.globalAlpha=alpha;this.ctx.drawImage(image,(cell%2)*sw,Math.floor(cell/2)*sh,sw,sh,x,y,sw*scale,sh*scale);this.ctx.restore();return {x,y,scale,sw,sh};}
 ivan(x,feet,height,{rotation=0,walk=false,battered=false}={}){const image=walk?this.images.ivanRight:this.images.ivan;if(!image.complete||!image.naturalWidth)return;const c=this.ctx,fw=image.naturalWidth/2,fh=image.naturalHeight,width=height*fw/fh,frame=walk?Math.floor(this.time/.28)%2:0;c.save();c.translate(x,feet);c.rotate(rotation);c.imageSmoothingEnabled=false;c.drawImage(image,frame*fw,0,fw,fh,-width/2,-height,width,height);
  if(battered){c.fillStyle='#694c35aa';c.fillRect(-width*.24,-height*.36,width*.23,height*.09);c.fillStyle='#e3d8b9';c.save();c.translate(-width*.04,-height*.85);c.rotate(-.25);c.fillRect(-width*.13,0,width*.26,height*.025);c.restore();}c.restore();}
 posters(transform,alpha){if(!transform)return;const {x,y,scale,sw,sh}=transform,c=this.ctx,image=this.images.wanted;if(!image.complete||!image.naturalWidth)return;c.save();c.globalAlpha=alpha;
  for(const [px,py,portrait] of [[.49,.25,1],[.585,.225,0],[.675,.26,1]]){const left=x+sw*px*scale,top=y+sh*py*scale,width=sw*.075*scale,height=sh*.155*scale;c.drawImage(image,portrait*image.naturalWidth/2,0,image.naturalWidth/2,image.naturalHeight,left,top,width,height);c.fillStyle='#26221f';c.font=`bold ${Math.max(6,width*.13)}px Georgia`;c.textAlign='center';c.fillText(window.I18n?.lang==='en'?'WANTED':'SE BUSCA',left+width/2,top+height*.17);c.fillText(portrait?'DR. ERIC':'KARLA',left+width/2,top+height*.84);}c.restore();}
 draw(){if(!this.item)return;const c=this.ctx,w=this.canvas.width,h=this.canvas.height,t=this.time;c.imageSmoothingEnabled=false;c.fillStyle='#081322';c.fillRect(0,0,w,h);let caption='';const newspaper=document.querySelector('#cinema-newspaper'),line=document.querySelector('#cinema-ivan-line');newspaper.hidden=!(this.item.id==='ivan-descenso'&&t>=16&&t<24);line.hidden=!(this.item.id==='ivan-descenso'&&t>=24&&t<28);
  const ericLine=document.querySelector('#cinema-eric-line');ericLine.hidden=true;
  if(this.item.id==='intercepcion-espacial'){const scene=this.space.draw(t);caption=scene.caption;ericLine.hidden=!scene.speech;if(ericLine.dataset.source!==scene.speech){ericLine.dataset.source=scene.speech;ericLine.textContent=scene.speech;}}
  else if(this.item.id==='ignitia-launch'){
   const flight=RocketFinaleScene.state(t),player={x:3,y:7.5,angle:0,pitch:flight.pitch,jumpHeight:0};this.legacy.time=t;this.legacyRenderer.draw(this.legacy.scene,player,false,0,t*1000,null,null);this.legacyRenderer.outdoor.draw(this.legacyRenderer,this.legacy.scene,player,this.legacyRenderer.actors,t*1000);this.legacy.draw(this.legacyRenderer,player,this.legacyRenderer.actors);
   caption=t<4?'Paola: «¡Espera! Algo se mueve detrás del cohete…»':t<8.5?'Iván busca a Eric… y tropieza con un cable.':t<19?'¡Pasajero inesperado! Iván va rumbo a las estrellas.':t<27?'Iván se suelta. El cohete pierde el control.':t<33?'El cohete cae fuera de cuadro.':'José Luis: «Ese era nuestro mejor cohete… Tendremos que diseñar uno nuevo». Finalmente, ¿qué fue de Iván?';
  }else{
   const phase=IvanDescent.state(t);this.player.dataset.phase=phase;
   if(t<6){this.background(0);const impact=3,ground=h*.82;if(t<impact){const u=t/impact;this.ivan(w*.37,-h*.18+(ground+h*.18)*u*u,h*.32,{rotation:u*Math.PI*2});}else{this.ivan(w*.43,ground-h*.08,h*.32,{rotation:Math.PI/2,battered:true});c.fillStyle='#c2af7899';for(let i=0;i<9;i++){const age=t-3,r=Math.max(0,1-age/2)*h*.035;c.beginPath();c.arc(w*.37+Math.cos(i)*age*w*.05,ground-Math.sin(i)*age*h*.035,r,0,Math.PI*2);c.fill();}c.fillStyle='#ffe8a6';c.font=`${h*.03}px serif`;for(let i=0;i<3;i++)c.fillText('✦',w*.4+Math.cos(t*2+i*2)*w*.045,ground-h*.22+Math.sin(t*2+i*2)*h*.025);}
    caption=t<3?'Mientras tanto, sobre el bosque…':'Iván: «Aterrizaje… casi controlado». Un poco maltrecho, pero todavía en pie.';
   }else if(t<12){this.background(1);const u=(t-6)/6;this.ivan(w*(.14+.52*u),h*(.88-.18*u),h*(.32-.13*u),{walk:true,battered:true});caption='Entre los árboles, Iván descubre una cabaña. Una vieja marca en la puerta le resulta familiar.';
   }else{const transform=this.background(2),light=Math.max(0,Math.min(1,(t-28)/.8));c.fillStyle='rgba(0,3,10,.70)';c.fillRect(0,0,w,h);if(light)this.background(3,light);this.posters(transform,.04+.96*light);c.save();c.filter=`brightness(${.27+.73*light})`;this.ivan(w*.22,h*.90,h*.38,{battered:true});c.restore();
    if(t<16){c.save();c.filter='brightness(.28)';c.translate(w*.81,h*.62);c.rotate(.12);const paper=this.images.wanted;if(paper.complete&&paper.naturalWidth)c.drawImage(paper,0,0,paper.naturalWidth/2,paper.naturalHeight,-w*.05,-h*.02,w*.1,h*.055);c.restore();caption='En el cobertizo encuentra el legado de Eric: cuadernos, experimentos y un periódico olvidado.';}
    else if(t<24){newspaper.hidden=false;caption='Una nota del periódico revela a otra posible aliada.';}
    else if(t<28){line.hidden=false;caption='Iván: «Parece que todavía tengo aliados…»';}
    else caption='Se enciende la luz. El laboratorio secreto de Eric seguía esperando a su próximo visitante.';
   }
  }
  const cap=document.querySelector('#cinema-caption');if(cap.dataset.source!==caption){cap.dataset.source=caption;cap.textContent=caption;}
  document.querySelector('#cinema-end').hidden=!this.finished;const timeText=`${Math.floor(t)} / ${this.item.duration} s`;if(document.querySelector('#cinema-time').textContent!==timeText)document.querySelector('#cinema-time').textContent=timeText;
 }
};
