/* Enunciados y soluciones originales. Referencia temática: Serway & Jewett, cinemática 1D/2D. */
window.PHYSICS_PROBLEMS = [
 {id:1,title:'Frenada en la pista celeste',topic:'MRUA',text:'Un vehículo de ensayo viaja a 27 m/s. El operador tarda 0.65 s en reaccionar, manteniendo esa velocidad. Después frena con aceleración constante de −4.5 m/s² hasta detenerse. Calcula la distancia total desde que detecta el obstáculo y el tiempo total.',fields:[['Distancia total','m',98.55],['Tiempo total','s',6.65]],hint:'Separa reacción y frenado. Durante la reacción a = 0.',solution:'Reacción: dᵣ = 27(0.65) = 17.55 m. Frenado: t_f = 27/4.5 = 6 s; d_f = 27²/(2·4.5) = 81 m. Total: d = 98.55 m y t = 6.65 s.'},
 {id:2,title:'Encuentro de dos transportadores',topic:'MRUA',text:'En t = 0, un transportador A pasa por x = 0 a 8 m/s y acelera a 1.2 m/s². En ese mismo instante, B está en x = 60 m y avanza en el mismo sentido a 4 m/s constantes. ¿En qué tiempo alcanza A a B y en qué posición?',fields:[['Tiempo de alcance','s',(-4+Math.sqrt(160))/1.2],['Posición de encuentro','m',60+4*((-4+Math.sqrt(160))/1.2)]],hint:'Iguala xA = 8t + 0.6t² y xB = 60 + 4t. Elige la raíz positiva.',solution:'0.6t² + 4t − 60 = 0. La raíz física es t = (−4 + √160)/1.2 = 7.21 s. Sustituye en xB: x ≈ 88.83 m.'},
 {id:3,title:'La caída entre sensores',topic:'Caída libre',text:'Una esfera se suelta desde el reposo. Dos sensores están separados verticalmente 12 m; la esfera tarda 0.40 s en viajar del superior al inferior. Calcula la rapidez al pasar por el sensor superior y la distancia entre el punto de suelta y ese sensor.',fields:[['Rapidez en el sensor superior','m/s',(12-.5*9.81*.4**2)/.4],['Altura de caída previa','m',((12-.5*9.81*.4**2)/.4)**2/(2*9.81)]],hint:'En el tramo entre sensores, 12 = v·0.40 + ½g·0.40². Después usa v² = 2gh.',solution:'v = (12 − 0.7848)/0.40 = 28.038 m/s. La caída previa es h = v²/(2g) ≈ 40.07 m.'},
 {id:4,title:'Mensajero desde la torre',topic:'Tiro parabólico',text:'Desde una torre de 35 m se lanza una cápsula a 22 m/s y 32° sobre la horizontal. El terreno de llegada es horizontal, a la base de la torre. Calcula el tiempo hasta impactar y el alcance horizontal.',fields:[['Tiempo de vuelo','s',(22*Math.sin(32*Math.PI/180)+Math.sqrt((22*Math.sin(32*Math.PI/180))**2+2*9.81*35))/9.81],['Alcance horizontal','m',22*Math.cos(32*Math.PI/180)*(22*Math.sin(32*Math.PI/180)+Math.sqrt((22*Math.sin(32*Math.PI/180))**2+2*9.81*35))/9.81]],hint:'Resuelve 0 = 35 + v₀y t − ½gt². Usa la raíz positiva para hallar x.',solution:'v₀x = 22 cos32° y v₀y = 22 sen32°. t = [v₀y + √(v₀y² + 2g·35)]/g ≈ 4.11 s. R = v₀x t ≈ 76.72 m.'},
 {id:5,title:'Cruzar el arco de piedra',topic:'Tiro parabólico',text:'Una esfera sale desde el suelo a 25 m/s con elevación de 40°. Un arco está a 30 m horizontales y su travesaño a 10 m de altura. ¿A qué altura pasa la esfera por el plano del arco y cuál es su velocidad vertical allí? Usa signo positivo hacia arriba.',fields:[['Altura en el arco','m',30*Math.tan(40*Math.PI/180)-9.81*30**2/(2*25**2*Math.cos(40*Math.PI/180)**2)],['Velocidad vertical','m/s',25*Math.sin(40*Math.PI/180)-9.81*30/(25*Math.cos(40*Math.PI/180))]],hint:'Primero t = 30/(25 cos40°). Luego calcula y y vy; compara y con 10 m.',solution:'t ≈ 1.57 s. y = v₀y t − ½gt² ≈ 13.14 m y vy = v₀y − gt ≈ +0.70 m/s. Pasa por encima del travesaño, aún ascendiendo.'},
 {id:6,title:'Ascenso sobre la plataforma',topic:'Caída libre',text:'Una plataforma sube verticalmente a 3 m/s. Desde ella, a 20 m sobre el suelo, se lanza una esfera hacia arriba a 7 m/s respecto de la plataforma. Calcula la altura máxima sobre el suelo y el tiempo hasta tocar el suelo.',fields:[['Altura máxima','m',20+100/(2*9.81)],['Tiempo hasta el suelo','s',(10+Math.sqrt(100+2*9.81*20))/9.81]],hint:'La rapidez inicial respecto al suelo es 3 + 7 = 10 m/s.',solution:'v₀ = 10 m/s. yₘáx = 20 + 10²/(2g) ≈ 25.10 m. Resuelve 0 = 20 + 10t − ½gt²: t ≈ 3.28 s.'},
 {id:7,title:'La maniobra del aerodeslizador',topic:'MRUA',text:'Un aerodeslizador parte del reposo y acelera a 2.4 m/s² durante 8 s. Después mantiene esa velocidad 5 s y finalmente frena a −3.2 m/s² hasta detenerse. Calcula la distancia total y la rapidez media de todo el recorrido.',fields:[['Distancia total','m',230.4],['Rapidez media','m/s',230.4/19]],hint:'Suma distancias y tiempos de tres fases. La rapidez media es distancia total / tiempo total.',solution:'Fase 1: v = 19.2 m/s y d₁ = 76.8 m. Fase 2: d₂ = 96 m. Fase 3: t₃ = 6 s y d₃ = 57.6 m. D = 230.4 m, T = 19 s, rapidez media ≈ 12.13 m/s.'},
 {id:8,title:'Dos rutas hacia el cristal',topic:'Tiro parabólico',text:'Un blanco está a 40 m, a la misma altura que el lanzamiento. La rapidez inicial es 24 m/s. Encuentra los dos ángulos de elevación que permiten alcanzarlo, en orden de menor a mayor.',fields:[['Ángulo menor','°',Math.asin(9.81*40/24**2)*90/Math.PI],['Ángulo mayor','°',90-Math.asin(9.81*40/24**2)*90/Math.PI]],hint:'R = v₀² sen(2θ)/g. El seno tiene dos soluciones en 0° < 2θ < 180°.',solution:'sen(2θ) = 392.4/576 = 0.68125. θ₁ = ½ arcsen(0.68125) ≈ 21.47° y θ₂ = 90° − θ₁ ≈ 68.53°.'},
 {id:9,title:'Intercepción de la baliza móvil',topic:'Avanzado · Tiro parabólico',hard:true,text:'Un lanzador está en (x,y) = (0,0). Una baliza se mueve a altura constante y = 12 m y, al disparar, está en x = 30 m alejándose a 4 m/s. El proyectil sale a 25 m/s. Determina el primer tiempo positivo de intercepción y su ángulo de elevación. Puedes resolver numéricamente. Trata la baliza y el proyectil como puntos.',fields:[['Primera intercepción','s',1.941460507482344],['Ángulo de elevación','°',38.9138455925449]],hint:'En la intercepción: v₀x = 30/t + 4 y v₀y = 12/t + ½gt. Impón v₀x² + v₀y² = 25² y busca la primera raíz positiva.',solution:'F(t) = (30/t + 4)² + (12/t + 4.905t)² − 625 = 0. Existen dos raíces positivas. La menor da t ≈ 1.94 s; θ = atan2(12/t + 4.905t, 30/t + 4) ≈ 38.91°. La otra solución describe un arco más alto.'},
 {id:10,title:'La energía mínima del portal',topic:'Avanzado · Optimización',hard:true,text:'Un portal puntual está 28 m adelante y 9 m por encima del lanzador. Sin rozamiento, determina la mínima rapidez inicial que permite alcanzarlo y el ángulo correspondiente. Se permite cualquier ángulo entre 0° y 90°. Explica por qué 45° ya no es el óptimo.',fields:[['Rapidez mínima','m/s',Math.sqrt(9.81*(9+Math.hypot(28,9)))],['Ángulo óptimo','°',Math.atan((9+Math.hypot(28,9))/28)*180/Math.PI]],hint:'Usa y = x tanθ − gx²(1 + tan²θ)/(2v₀²). En el mínimo, la ecuación cuadrática en tanθ tiene una única raíz.',solution:'Discriminante cero: vₘín² = g[y + √(x² + y²)]. Para x = 28 m e y = 9 m: vₘín ≈ 19.41 m/s. tanθ = [y + √(x² + y²)]/x, de donde θ ≈ 53.91°. El blanco está más alto; el ángulo óptimo supera 45°.'}
];
