window.ProblemRoulette=class {
 constructor(onSolve){this.onSolve=onSolve;this.reset();document.querySelector('#answer-form').onsubmit=e=>{e.preventDefault();this.check();};}
 reset(){this.angle=0;this.spinning=false;this.current=null;this.remaining=PHYSICS_PROBLEMS.map((_,i)=>i);this.solved=new Set();this.elapsed=0;this.tickSector=-1;document.querySelector('#problem-card').hidden=true;document.querySelector('#roulette-status').textContent='Pulsa el botón de la mesa para invocar un desafío.';document.querySelector('#answer-feedback').textContent='';}
 spin(){if(this.spinning)return;Sound.click();if(!this.remaining.length){document.querySelector('#roulette-status').textContent='Has visto los diez problemas. Reinicia la rueda para otra ronda.';return;}
 const random=new Uint32Array(1);crypto.getRandomValues(random);const chosen=random[0]%this.remaining.length;this.selected=this.remaining.splice(chosen,1)[0];this.startAngle=this.angle;const sector=Math.PI*2/10,target=-Math.PI/2-(this.selected+.5)*sector;this.endAngle=this.angle+Math.PI*2*5+((target-this.angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);this.elapsed=0;this.spinning=true;this.current=null;document.querySelector('#problem-card').hidden=true;document.querySelector('#roulette-status').textContent='La rueda gira…';}
 tick(dt){if(!this.spinning)return;this.elapsed+=dt;const u=Math.min(1,this.elapsed/3.8);this.angle=this.startAngle+(this.endAngle-this.startAngle)*(1-(1-u)**3);const sector=Math.floor(this.angle/(Math.PI/5));if(sector!==this.tickSector){Sound.tick();this.tickSector=sector;}if(u===1){this.spinning=false;this.present(this.selected);Sound.click();}}
 present(i){this.current=PHYSICS_PROBLEMS[i];const q=this.current;document.querySelector('#problem-card').hidden=false;document.querySelector('#problem-level').textContent=`${String(q.id).padStart(2,'0')} / ${q.topic}`;document.querySelector('#problem-level').classList.toggle('hard',!!q.hard);document.querySelector('#problem-title').textContent=q.title;document.querySelector('#problem-text').textContent=q.text;document.querySelector('#problem-hint').textContent=q.hint;document.querySelector('#problem-solution').textContent=q.solution;document.querySelector('#hint-details').open=document.querySelector('#solution-details').open=false;document.querySelector('#answer-feedback').textContent='';const fields=document.querySelector('#answer-fields');fields.replaceChildren();q.fields.forEach(([name,unit],j)=>{const label=document.createElement('label');label.textContent=`${name} (${unit})`;const input=document.createElement('input');input.id=`answer-${j}`;input.type='text';input.inputMode='decimal';input.autocomplete='off';input.required=true;label.append(input);fields.append(label);});document.querySelector('#roulette-status').textContent=`Desafío ${q.id} seleccionado · ${this.remaining.length} por descubrir · ${this.solved.size} resueltos`;}
 check(){if(!this.current||this.spinning)return;if(this.canAnswer&&!this.canAnswer()){document.querySelector('#answer-feedback').textContent='Acércate a la segunda mesa y mira el panel verde para responder.';return;}const q=this.current,values=q.fields.map((_,j)=>{const raw=document.querySelector(`#answer-${j}`).value.trim().replace(',','.');return raw!==''&&/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[-+]?\d+)?$/i.test(raw)?Number(raw):NaN;});if(values.some(v=>!Number.isFinite(v))){document.querySelector('#answer-feedback').textContent='Introduce números válidos, sin unidades. Puedes usar coma o punto decimal.';return;}
 const correct=q.fields.map((f,i)=>Math.abs(values[i]-f[2])<=Math.max(.02,Math.abs(f[2])*.01));if(correct.every(Boolean)){this.solved.add(q.id);document.querySelector('#answer-feedback').textContent='✦ Respuesta correcta. El sello de la puerta se ha abierto. Puedes continuar o girar otra vez.';Sound.success();this.onSolve();}else{document.querySelector('#answer-feedback').textContent=correct.map((ok,i)=>`${q.fields[i][0]}: ${ok?'correcto':'revisa el planteamiento y las unidades'}`).join(' · ');Sound.tone(180,.2,'triangle',.15);}}
};
