const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.requestAnimationFrame=()=>0;});await p.goto(process.env.GAME_URL||'http://127.0.0.1:8765');fs.mkdirSync('/tmp/epik',{recursive:true});
 assert.match(await p.title(),/Aventura EPIK/);assert.match(await p.locator('.brand').textContent(),/AVENTURA EPIK/);await p.waitForFunction(()=>prologue.images.paola.complete&&prologue.images.paola.naturalWidth);await p.evaluate(()=>{prologue.started=true;prologue.renderPage();prologue.elapsed=.13;prologue.drawFace();});const mouthA=await p.locator('#story-face').screenshot();await p.evaluate(()=>{prologue.elapsed=.26;prologue.drawFace();});const mouthB=await p.locator('#story-face').screenshot();assert(!mouthA.equals(mouthB));assert.equal(await p.locator('#story-face').getAttribute('height'),'224');await p.locator('#adventure-intro').screenshot({path:'/tmp/epik/paola.png'});
 await p.locator('#story-skip').click();await p.locator('#maze-understood').click();await p.waitForFunction(()=>Number.isFinite(Sound.tracks.bridge.duration));assert.equal(await p.evaluate(()=>Sound.tracks.bridge.duration),2);
 await p.evaluate(()=>{document.querySelector('#effects-volume-mute').checked=true;Sound.apply();});assert.equal(await p.evaluate(()=>Sound.tracks.bridge.volume),0);await p.evaluate(()=>{document.querySelector('#effects-volume-mute').checked=false;Sound.apply();trial.stage=2;trial.broken.add('0:true');trialEvent('safe',{x:8,y:3});die('pit');respawn();});assert.deepEqual(await p.evaluate(()=>[player.x,player.y,trial.stage,trial.broken.has('0:true')]),[2.5,3.85,2,true]);
 await p.evaluate(()=>{load(1);document.querySelector('#maze-notice').hidden=true;Object.assign(player,{x:1.8,y:3.5,angle:0,pitch:.12});tick(16);});await p.locator('.scene-view').screenshot({path:'/tmp/epik/exams.png'});
 const quotes=[];for(let i=0;i<3;i++){
  await p.evaluate(()=>{load(4);document.querySelector('#maze-notice').hidden=true;boss.potions.pools=[{x:player.x,y:player.y,expires:10}];boss.potions.tick(.01,player);death.startedAt=performance.now()-250;tick(last+16);});assert.equal(await p.evaluate(()=>death.type),'potion');
  if(i===0)await p.locator('.scene-view').screenshot({path:'/tmp/epik/green-flash.png'});
  await p.evaluate(()=>{death.startedAt=performance.now()-2000;animateDeath(0);});quotes.push(await p.locator('#death-quote').textContent());await p.evaluate(()=>respawn());
 }
 assert.equal(new Set(quotes).size,3);assert(quotes.every(q=>!/gravedad/i.test(q)));assert.match(quotes[0],/exotérmica/);assert.match(quotes[2],/reactivos/);
 await p.evaluate(()=>{boss.potions.reset();boss.potions.bottles=[{x:15,y:7.5,age:1.5}];boss.potions.tick(.2,{x:1,y:1});});assert.equal(await p.evaluate(()=>boss.potions.bursts.length),1);await p.evaluate(()=>boss.potions.tick(.8,{x:1,y:1}));assert.equal(await p.evaluate(()=>boss.potions.bursts.length),0);
 assert.equal(await p.evaluate(()=>IVAN_CHASE_SPEED),.8751645);assert.deepEqual(await p.evaluate(()=>InterceptionPhysics.ericVelocity),{x:.231,y:.105});assert.deepEqual(errors,[]);await b.close();console.log('PASS: EPIK branding, animated torso, 2s bridge audio/mute, origin respawn with progress and broken wood, exams, three chemistry messages, green burst lifetime and speeds.');
})().catch(e=>{console.error(e);process.exit(1)});
