const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const out=process.env.SCREENSHOT_DIR||'/tmp/astralia-ending';fs.mkdirSync(out,{recursive:true});
async function passDialogueScene(){await page.evaluate(()=>{const id=cinematics.item.id;cinematics.paused=false;if(!cinematics.dialogueStops){for(let t=0;t<70&&cinematics.item?.id===id;t++)cinematics.tick(1);return;}for(let i=cinematics.dialogueIndex;i<cinematics.dialogueStops.length&&cinematics.item?.id===id;i++){cinematics.time=cinematics.dialogueStops[i];cinematics.dialogueWaiting=true;cinematics.inputAfter=0;cinematics.advanceDialogue();}});}
await page.goto(process.env.GAME_URL||'http://127.0.0.1:8765');await page.locator('#story-skip').click();await page.locator('#maze-understood').click();await page.waitForFunction(()=>Object.values(cinematics.images).every(i=>i.complete&&i.naturalWidth));
await page.evaluate(()=>{load(0);document.querySelector('#maze-notice').hidden=true;Object.assign(player,{x:3.7,y:4,angle:Math.PI,pitch:0});companions.help();companions.finishDialogue();});assert.match(await page.locator('#paola-text').textContent(),/seis ecuaciones.*Una de ellas/);await page.evaluate(()=>companions.closeHelp());await page.locator('#game').screenshot({path:out+'/chalk.png'});
await page.evaluate(()=>{load(1);document.querySelector('#maze-notice').hidden=true;companions.help();companions.finishDialogue();});assert.match(await page.locator('#paola-text').textContent(),/cristal.*mesa.*datos.*sello/);
await page.evaluate(()=>{load(4);document.querySelector('#maze-notice').hidden=true;Object.assign(player,{x:10.3,y:2.2,angle:0});boss.open(player,renderer,rooms[index],opened);});await page.locator('#boss-x').fill('0');await page.locator('#boss-y').fill('0');await page.locator('#boss-form button').click();assert(await page.locator('#boss-panel').isVisible());const leftRoot=await page.evaluate(()=>boss.puzzle.support.intersections[0]);await page.locator('#boss-x').fill(String(leftRoot[0]));await page.locator('#boss-y').fill(String(leftRoot[1]));await page.locator('#boss-form button').click();assert(await page.locator('#boss-panel').isHidden());
await page.evaluate(()=>{Object.assign(player,{x:10.3,y:12.8,angle:0});boss.open(player,renderer,rooms[index],opened);});const rightRoot=await page.evaluate(()=>boss.puzzle.support.intersections[1]);await page.locator('#boss-x').fill(String(rightRoot[0]));await page.locator('#boss-y').fill(String(rightRoot[1]));await page.locator('#boss-form button').click();assert(await page.locator('#boss-panel').isHidden());assert.equal(await page.evaluate(()=>boss.puzzle.solved),true);
await page.evaluate(()=>{load(5);document.querySelector('#maze-notice').hidden=true;Object.assign(player,{x:6,y:5.5,angle:0});ignitia.open(player);window.flow=[];const play=cinematics.play.bind(cinematics);cinematics.play=(id,options)=>{flow.push(id);return play(id,options);};window.soundCues=[];const playSound=Sound.play.bind(Sound);Sound.play=(name,...args)=>{soundCues.push(name);return playSound(name,...args);};const s=ignitia.simulator;s.missionTime=20;const duration=100,delay=10,t=20+duration+delay,vx=InterceptionPhysics.eric(t).x/duration,vy=(InterceptionPhysics.eric(t).y+.5*.00981*duration*duration)/duration;s.params={speed:Math.hypot(vx,vy),angle:Math.atan2(vy,vx)*180/Math.PI,delay,duration};s.sync();s.startTrial();for(let n=0;n<200&&s.running;n++)s.tick(.04);});
await page.waitForFunction(()=>cinematics.item?.id==='ignitia-intercepcion');assert.equal(await page.evaluate(()=>cinematics.missionEnding.space.plan.selected),true);assert.equal(await page.evaluate(()=>cinematics.missionEnding.world.scene===rooms[5]),true);assert.equal(await page.locator('#cinema-player').getAttribute('data-presentation'),'world');const aligned=await page.evaluate(()=>{const a=document.querySelector('#cinema-player').getBoundingClientRect(),b=document.querySelector('.scene-view').getBoundingClientRect();return Math.abs(a.x-b.x)<2&&Math.abs(a.y-b.y)<2&&Math.abs(a.width-b.width)<2&&Math.abs(a.height-b.height)<2;});assert(aligned,'La escena ocupa la misma vista del juego');assert(await page.locator('#rocket-console').isHidden());
await page.evaluate(()=>{ignitia.startLaunch();ignitia.startLaunch();cinematics.paused=true;});assert.deepEqual(await page.evaluate(()=>flow),['ignitia-intercepcion']);
for(const [label,t] of [['walk',4.5],['tangle',8],['hanging',16],['fall',21],['orbit',30],['impact',36.7],['prison',55]]){await page.evaluate(t=>{cinematics.time=t;cinematics.audio();cinematics.draw();},t);await page.locator('#cinema-player').screenshot({path:out+'/'+label+'.png'});}
const route=await page.evaluate(()=>{const s=SpaceInterception.position(cinematics.missionEnding.space.plan,1);return Math.hypot(s.ours.x-s.eric.x,s.ours.y-s.eric.y);});assert(route<1e-6);assert.equal(await page.evaluate(()=>soundCues.filter(n=>n==='rocket').length),1);assert.equal(await page.evaluate(()=>soundCues.filter(n=>n==='explosion').length),1);
await passDialogueScene();assert.equal(await page.evaluate(()=>cinematics.item.id),'ceremonia-karla');assert.equal(await page.evaluate(()=>completed),true);assert(await page.locator('#ceremony-preview').isHidden());
await page.evaluate(()=>{cinematics.paused=true;cinematics.time=9.3;cinematics.draw();});await page.locator('#cinema-player').screenshot({path:out+'/tablet.png'});
await passDialogueScene();await page.evaluate(()=>cinematics.tick(60));assert(await page.locator('#ceremony-certificate').isVisible());assert.deepEqual(await page.evaluate(()=>flow),['ignitia-intercepcion','ceremonia-karla']);
await page.setViewportSize({width:390,height:844});await page.locator('#cinema-player').screenshot({path:out+'/diploma-mobile.png'});const fits=await page.locator('#certificate-continue').evaluate(b=>{const a=b.getBoundingClientRect(),c=b.closest('article').getBoundingClientRect();return a.bottom<=c.bottom&&a.top>=c.top&&a.top>=0&&a.bottom<=innerHeight;});assert(fits,'Diploma button stays inside certificate');
await page.waitForTimeout(460);await page.evaluate(()=>{const button=document.querySelector('#certificate-continue');button.click();button.click();document.querySelector('#cinema-close').click();});assert.equal(await page.evaluate(()=>cinematics.item.id),'ivan-descenso');assert.equal(await page.evaluate(()=>flow.filter(x=>x==='ivan-descenso').length),1);
await page.evaluate(()=>{cinematics.paused=true;cinematics.time=7;cinematics.draw();});await page.locator('#cinema-player').screenshot({path:out+'/secret.png'});await passDialogueScene();assert.equal(await page.evaluate(()=>ignitia.mode),'ending');assert(await page.locator('#chapter-ending').isVisible());assert.equal(await page.evaluate(()=>cinematics.active),false);
// A gallery preview still cannot complete a game or reveal the secret via its certificate.
await page.evaluate(()=>{load(0);document.querySelector('#maze-notice').hidden=true;cinematics.open();cinematics.play('ceremonia-karla');cinematics.finish();});await page.waitForTimeout(460);await page.locator('#certificate-continue').click();assert.equal(await page.evaluate(()=>completed),false);assert.equal(await page.evaluate(()=>cinematics.active),false);
// Closing early advances the current dialogue; only closing the certificate reveals the secret.
await page.evaluate(()=>{cinematics.play('ceremonia-karla',{story:true,onComplete:()=>{window.secretCalls=(window.secretCalls||0)+1;cinematics.play('ivan-descenso',{story:true});}});});await page.waitForTimeout(470);await page.keyboard.press('Escape');assert(await page.locator('#ceremony-certificate').isHidden());await passDialogueScene();assert(await page.locator('#ceremony-certificate').isVisible());assert.equal(await page.evaluate(()=>window.secretCalls||0),0);await page.waitForTimeout(470);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>secretCalls),1);assert.equal(await page.evaluate(()=>cinematics.item.id),'ivan-descenso');
await page.evaluate(()=>{cinematics.close();I18n.set('en');load(0);document.querySelector('#maze-notice').hidden=true;mission.restart();companions.help();companions.finishDialogue();});assert.match(await page.locator('#paola-text').textContent(),/six chalk equations/);
assert.deepEqual(errors,[]);await browser.close();console.log('OK: rear equations, room 2 help, changed laser answers, automatic single launch, cable/fall, exact confirmed interception, prison, ceremony/tablet, diploma waits, mobile, double-click guard, secret then exit, gallery isolation; zero JS errors.');})().catch(e=>{console.error(e);process.exit(1)});
