const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),w={};w.window=w;vm.createContext(w);
for(const f of ['src/rooms/room-01/room.js','src/rooms/room-03/maze.js'])vm.runInContext(fs.readFileSync(f,'utf8'),w);
const room=w.ESCAPE_ROOMS[0];assert.equal((room.bridge.end-room.bridge.start)*2,30*.75);assert.equal(room.floorTile(17.24,3.5),3);assert.equal(room.floorTile(17.25,3.5),0);assert.equal(room.floorTile(17.9,3.5),0);assert.equal(room.floorTile(17.5,0),1);assert.equal(room.physics.targetX,19);
const m=new w.ConceptMaze({spawn:{x:2.5,y:8.5},environment:{kind:'interior'}},()=>{}),renderer={cast:()=>({distance:2})};assert.equal(m.freezeButton,null);
for(const stage of [1,2,3]){m.stage=stage;const b=m.freezeButton,p={x:b.x,y:2.5,angle:-Math.PI/2};assert.equal(m.room.map[0][Math.floor(b.x)],1);assert.equal(m.room.map[1][Math.floor(b.x)],0);assert(!m.activateFreeze({...p,angle:0},renderer));assert(!m.activateFreeze({...p,y:5},renderer));assert(!m.activateFreeze(p,{cast:()=>({distance:.1})}));m.tick(0,p);assert.equal(m.freezeUsed,false);assert(m.activateFreeze(p,renderer));assert.equal(m.freezeLeft,10);m.tick(2,p);const left=m.freezeLeft;assert(m.activateFreeze(p,renderer));assert.equal(m.freezeLeft,left,'No recarga al pulsar repetidamente');}
m.stage=2;m.enterDungeon({},m.doors.find(d=>!d.correct));const b=m.freezeButton,p={x:b.x,y:2.5,angle:-Math.PI/2};assert(!m.freezeUsed);assert(m.activateFreeze(p,renderer));assert.equal(m.freezeLeft,10);m.leaveDungeon();m.stage=2;assert(m.freezeUsed,'Volver no recarga botones de las galerías');m.enterDungeon({},m.doors.find(d=>!d.correct));assert(!m.freezeUsed,'Nueva visita recarga solo el botón del calabozo');m.finished=true;assert.equal(m.freezeButton,null);
console.log('OK: vacío -25 % exacto, botones de pared en tramos 2–4 y calabozo, interacción, alcance, obstrucción y usos independientes.');

const exact=new w.ConceptMaze({spawn:{x:2.5,y:8.5},environment:{kind:'interior'}},()=>{});exact.stage=2;exact.awaken(true);exact.grace=0;const target={x:30.5,y:2.5,angle:-Math.PI/2};exact.activateFreeze(target,renderer);const start={...exact.enemy};exact.tick(9.75,target);assert.equal(exact.enemy.x,start.x);assert.equal(exact.enemy.y,start.y);exact.tick(.5,target);const moved=Math.hypot(exact.enemy.x-start.x,exact.enemy.y-start.y);assert(Math.abs(moved-.25*.72*1.05**3)<1e-9,'Solo se mueve durante los 0.25 s posteriores al efecto');
