const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.requestAnimationFrame=()=>0;});await p.goto(process.env.GAME_URL||'http://127.0.0.1:8765');await p.locator('#story-skip').click();await p.locator('#maze-understood').click();
 await p.evaluate(()=>{load(0);document.querySelector('#maze-notice').hidden=true;lab.mode.value='speed';lab.v.value='10';lab.a.value='35';lab.az.value='0';lab.selected=0;lab.launch(()=>{});});assert.equal(await p.evaluate(()=>lab.target.misses),0);
 for(let i=0;i<3;i++){await p.evaluate(()=>{lab.loadAmmo();lab.launch(()=>{throw Error('unexpected hit')});lab.tick(.1);});assert.equal(await p.evaluate(()=>rooms[0].physics.targetX),19,'No motion while shot is in flight');await p.evaluate(()=>lab.tick(20));}
 assert.equal(await p.evaluate(()=>lab.target.distance),25);assert.equal(await p.locator('#target-distance').textContent(),'25 m');assert.match(await p.locator('#feedback').textContent(),/Tres tiros fallidos/);assert.match(await p.locator('#attempts').textContent(),/x = 31 m/);
 await p.evaluate(()=>{companions.help();companions.finishDialogue();});assert.match(await p.locator('#paola-text').textContent(),/25 m/);await p.evaluate(()=>{companions.closeHelp();die('pit');respawn();});assert.equal(await p.evaluate(()=>lab.target.distance),25);
 // Third shot succeeding must open the bridge, not move the target.
 await p.evaluate(()=>{lab.target.misses=2;const D=lab.target.distance;lab.v.value=String(Math.sqrt(9.81*D*D/(D-3.3)));lab.a.value='45';lab.loadAmmo();lab.launch(()=>{opened=true;});lab.tick(20);});assert.equal(await p.evaluate(()=>opened),true);assert.equal(await p.evaluate(()=>lab.target.distance),25);
 await p.evaluate(()=>load(0));assert.equal(await p.evaluate(()=>lab.target.distance),31);
 await p.evaluate(()=>Promise.all(CINEMATICS.map(scene=>cinematics.assets.preload(scene.id))));
 for(const id of ['ceremonia-ignitia','ceremonia-karla']){
  await p.evaluate(id=>{cinematics.play(id);cinematics.tick(8);},id);const t=await p.evaluate(()=>cinematics.time),a=await p.locator('#cinema-canvas').screenshot();await p.evaluate(()=>cinematics.tick(.2));const next=await p.locator('#cinema-canvas').screenshot();assert.equal(await p.evaluate(()=>cinematics.time),t);assert(!a.equals(next),'Animation keeps moving while dialogue waits');
  const visual=await p.evaluate(()=>cinematics.visualTime);await p.evaluate(()=>{cinematics.inputAfter=0;cinematics.advanceDialogue();cinematics.advanceDialogue();});assert.equal(await p.evaluate(()=>cinematics.dialogueIndex),1);assert.equal(await p.evaluate(()=>cinematics.visualTime),visual,'Click never jumps the animation clock');await p.evaluate(()=>cinematics.tick(.1));assert(await p.evaluate(()=>cinematics.visualTime)>visual);
  await p.evaluate(()=>{cinematics.paused=true;});const paused=await p.evaluate(()=>cinematics.visualTime);await p.evaluate(()=>cinematics.tick(1));assert.equal(await p.evaluate(()=>cinematics.visualTime),paused);await p.evaluate(()=>cinematics.close());
 }
 assert(Math.abs(await p.evaluate(()=>Math.hypot(InterceptionPhysics.ericVelocity.x,InterceptionPhysics.ericVelocity.y))-.308)<1e-12);assert.deepEqual(errors,[]);await b.close();console.log('PASS: three misses, no midair movement, dynamic readout/help/history, respawn/reset, successful third shot, both smooth ceremonies with independent animation clock and double-click guard, 0.308 km/s.');
})().catch(e=>{console.error(e);process.exit(1)});
