/* Local translations for the DOM, projected labels and dialogue; progress is preserved. */
window.I18n={
 lang:(()=>{try{return localStorage.getItem('astralia-language')==='en'?'en':'es';}catch{return 'es';}})(),sources:new WeakMap(),cache:new Map(),
 t(text){if(this.lang!=='en'||typeof text!=='string')return text;if(!/[a-záéíóúñ]/i.test(text))return text;if(this.cache.has(text))return this.cache.get(text);const exact=ENGLISH[text];if(exact)return exact;let out=text;for(const [es,en] of this.entries)if(out.includes(es))out=out.split(es).join(en);if(this.cache.size>3000)this.cache.clear();this.cache.set(text,out);return out;},
 entries:Object.entries(ENGLISH).sort((a,b)=>b[0].length-a[0].length),
 node(n){if(n.nodeType===3){if(n.parentElement?.closest('script,style,[data-no-translate],#language-toggle'))return;const old=this.sources.get(n),source=old&&n.nodeValue===old.rendered?old.source:n.nodeValue,rendered=this.t(source);if(n.nodeValue!==rendered)n.nodeValue=rendered;this.sources.set(n,{source,rendered});}else if(n.nodeType===1){for(const attr of ['aria-label','placeholder','title','alt'])if(n.hasAttribute(attr)){n._i18n=n._i18n||{};const prior=n._i18n[attr],value=n.getAttribute(attr),source=prior&&value===prior.rendered?prior.source:value,rendered=this.t(source);n._i18n[attr]={source,rendered};if(value!==rendered)n.setAttribute(attr,rendered);}for(const child of n.childNodes)this.node(child);}},
 apply(){document.documentElement.lang=this.lang;this.node(document.body);const b=document.querySelector('#language-toggle');if(b){b.textContent=this.lang==='es'?'English':'Español';b.setAttribute('aria-label',this.lang==='es'?'Switch to English':'Cambiar a español');}},
 set(lang){this.lang=lang;try{localStorage.setItem('astralia-language',lang);}catch{}this.apply();window.dispatchEvent(new Event('astralia:language'));},
 start(){this.apply();document.querySelector('#language-toggle').onclick=()=>this.set(this.lang==='es'?'en':'es');new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')this.node(r.target);else if(r.type==='childList')for(const n of r.addedNodes)this.node(n);else this.node(r.target);}}).observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','placeholder','title','alt']});}
};
for(const method of ['fillText','strokeText','measureText']){const original=CanvasRenderingContext2D.prototype[method];CanvasRenderingContext2D.prototype[method]=function(text,...rest){return original.call(this,I18n.t(String(text)),...rest);};}
window.addEventListener('DOMContentLoaded',()=>I18n.start());
