/* Paola narra. El retrato central cambia sin revelar el encuentro del laberinto. */
window.AdventurePrologue=class {
 constructor(onEnter){
  this.onEnter=onEnter;this.step=0;this.started=false;this.done=false;this.elapsed=0;this.clock=0;this.count=0;this.speaking=false;
  this.pages=[
   {portrait:'paola',name:'Epi Paola',cue:'music',title:'Antes de cruzar el bosque…',text:'Hola, soy Epi Paola. Hay algo que debes saber antes de entrar al castillo. Todo empezó con el Dr. Eric… y unas gráficas.'},
   {portrait:'eric',name:'Dr. Eric',cue:'villain',title:'El origen de un villano',text:'Este es el Dr. Eric. Se cansó de que los alumnos nunca pusieran títulos a las gráficas. Su paciencia se convirtió en furia, y ahora prepara la divergencia: quiere unificar la gravedad y el espacio.'},
   {portrait:'paola',name:'Epi Paola',cue:'villain',title:'Una hora para detenerlo',text:'Nadie sabe qué podría ocurrir si termina su experimento. Te esperan seis umbrales y varias pruebas de física. Tendrás sesenta minutos desde que entres al mundo; usa tus conocimientos y observa a tu alrededor.'},
   {portrait:'ivan',name:'EPI Iván · desaparecido',cue:'missing',title:'Una desaparición sin resolver',text:'El EPI Iván también está desaparecido desde que Eric se fue. Nadie sabe dónde se encuentra. Se dice que se perdió en un bosque… pero nadie ha podido confirmar esa historia.'},
   {portrait:'paola',name:'Epi Paola',cue:'music',title:'No estarás solo',text:'Yo estaré para apoyarte. Puedes contar conmigo presionando la tecla H o tocando mi globo de ayuda. Ahora, respira, prepara tus cálculos y entra. Ah… y esta vez ponles título a tus gráficas.'}
  ];
  this.images={};for(const [name,file] of Object.entries({paola:'epi-paola-glasses-a-talk.webp',eric:'dr-eric.png',ivan:'epi-ivan.png'})){const img=new Image();img.src='assets/sprites/'+file;this.images[name]=img;}
  this.paolaBody=new Image();this.paolaBody.src='assets/cinematics/paola-glasses-a-gesture.webp';
  const dialog=document.querySelector('#adventure-intro');dialog.classList.add('prologue');dialog.setAttribute('aria-describedby','story-text');
  dialog.innerHTML=`<button id="story-language" class="story-language" data-no-translate>English / Español</button><p class="eyebrow">ASTRALIA · EPI PAOLA TE CUENTA</p><h2 id="adventure-title"></h2><div class="story-stage"><div class="story-portrait"><div class="missing-headline" hidden><span>LA GACETA DE ASTRALIA</span><strong>DESAPARECIDO</strong><small>EDICIÓN ESPECIAL · MISTERIO EN EL BOSQUE</small></div><canvas id="story-face" width="224" height="224" aria-label="Retrato de la historia"></canvas><span id="story-person"></span><p class="missing-caption" hidden>Último rastro: el bosque.<br>Su paradero sigue siendo un misterio.</p></div><div class="story-dialogue"><span class="story-speaker">EPI PAOLA</span><p id="story-text" aria-live="off"></p><p id="story-announcement" class="sr-only" role="status"></p></div></div><div class="story-footer"><span id="story-progress">PRÓLOGO · 1 / 5</span><span>El reloj aún no corre</span></div><button id="adventure-start" class="primary" autofocus>Escuchar a Paola</button><button id="story-skip" class="story-skip">Saltar relato y entrar</button>`;
  document.querySelector('#story-language').onclick=()=>I18n.set(I18n.lang==='es'?'en':'es');
  document.querySelector('#adventure-start').onclick=()=>this.advance();document.querySelector('#story-skip').onclick=()=>this.finish();dialog.addEventListener('cancel',e=>{e.preventDefault();this.finish();});this.renderPage();
 }
 renderPage(){const p=this.pages[this.step];this.chars=[...I18n.t(p.text)];this.count=0;this.clock=0;this.elapsed=0;this.speaking=this.started;
  const fullBody=p.portrait==='paola',face=document.querySelector('#story-face');face.width=fullBody?300:224;face.height=fullBody?440:224;document.querySelector('.story-portrait').classList.toggle('full-body',fullBody);
  const missing=p.portrait==='ivan';document.querySelector('.story-portrait').classList.toggle('missing-newspaper',missing);document.querySelector('.missing-headline').hidden=!missing;document.querySelector('.missing-caption').hidden=!missing;
  document.querySelector('#adventure-title').textContent=p.title;document.querySelector('#story-person').textContent=p.name;document.querySelector('#story-face').setAttribute('aria-label',p.name);document.querySelector('#story-text').textContent=this.started?'':'Una historia antes de la aventura. Pulsa «Escuchar a Paola» para comenzar.';document.querySelector('#story-announcement').textContent=this.started?p.text:'';
  document.querySelector('#story-progress').textContent=`PRÓLOGO · ${this.step+1} / ${this.pages.length}`;document.querySelector('#adventure-start').textContent=this.started?'Mostrar todo':'Escuchar a Paola';Sound.selectBackground(p.cue);this.drawFace();
 }
 advance(){if(this.done)return;if(!this.started){this.started=true;this.renderPage();return;}if(this.speaking){this.reveal();return;}if(this.step===this.pages.length-1){this.finish();return;}this.step++;this.renderPage();}
 reveal(){this.speaking=false;this.count=this.chars.length;document.querySelector('#story-text').textContent=I18n.t(this.pages[this.step].text);document.querySelector('#adventure-start').textContent=this.step===this.pages.length-1?'Entrar al mundo · 60 minutos':'Continuar';this.drawFace();}
 tick(dt){if(this.done)return;this.elapsed+=dt;this.clock-=dt;if(this.speaking&&this.clock<=0){const ch=this.chars[this.count++];document.querySelector('#story-text').textContent=this.chars.slice(0,this.count).join('');if(/[^\s.,…!?¿¡:;]/u.test(ch)&&this.count%2===0)Sound.dialogueBlip(this.count);this.clock=/[.!?…]/.test(ch)?.23:/[,;:]/.test(ch)?.1:.028;if(this.count>=this.chars.length)this.reveal();}this.drawFace();}
 drawFace(){const p=this.pages[this.step],img=this.images[p.portrait],canvas=document.querySelector('#story-face'),c=canvas.getContext('2d');if(p.portrait==='paola'){c.clearRect(0,0,canvas.width,canvas.height);CinematicSpriteMotion.draw(c,this.paolaBody,'paolaGesture',this.speaking?CinematicSpriteMotion.gestureFrame(this.elapsed):0,150,425,400,{speaking:this.speaking,time:this.elapsed});return;}c.clearRect(0,0,224,224);if(!img.complete||!img.naturalWidth)return;const frame=p.portrait==='ivan'?0:this.speaking?Math.floor(this.elapsed/(p.portrait==='eric'?.4:.13))%2:0,fw=img.naturalWidth/2;c.imageSmoothingEnabled=false;c.drawImage(img,frame*fw,0,fw,img.naturalHeight,0,0,224,224);}
 finish(){if(this.done)return;this.done=true;this.speaking=false;Sound.selectBackground('music');this.onEnter();}
};
